# Generated by Django 2.1.3 on 2018-11-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('color', models.CharField(default='black', max_length=255)),
                ('imageUrl', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
