# Generated by Django 2.1.3 on 2018-11-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_perro'),
    ]

    operations = [
        migrations.AddField(
            model_name='perro',
            name='estado',
            field=models.CharField(default='Rescatado', max_length=255),
        ),
    ]
